### ISSUE TITLE
Track event modification

### ISSUE THREAD

**Issue by Ceesaxp** [bobuk/gcalsync#4]
If an event that was previously synced gets modified (e.g. its date or time are changed), `gcalsync` does not update the 'clones'. Deleting 'clones' does not help either, since the `sync` has already been recorded.

Correcting this behaviour would require looking at whether "key" event parameters are the same between origin and clones. Storing the hash value of the origin event dates/times may be a relatively low-cost solution to this…

**Comment by bobuk** [comment]
had a time to check the whole idea and it sounds too complicated :(
may be the propper way to md5(summary+ description+ time) as a checksum and write it into a database. But still too complicated, looking for another solution.
If you have some ideas, feel free to share.

**Comment by Ceesaxp** [comment]
Yeah, I know. I've thought whether there is a simpler way, also thought about a set of fields that matter. Technically – we're only interested in date/time, since all we want to make sure is that we block the right spot. Then one could say that event title/summary also matters… Dunno… On my 4 calendars in sync it takes nearly a minute to just look through all of them even with no changes in place, doing another pass with md5 hash…

**Comment by Ceesaxp** [comment]
Ah! I think that what was already added (checking event.Updated vs local db) should be enough_ish_

**Comment by Ceesaxp** [comment]
Looks like implementation by @L0ndra with checking event.Updated vs. local storage is sufficient (at least for my use-case)
